#!/bin/sh

#
# Gradle start up script for POSIX generated by Gradle.
#

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

DIRNAME=`dirname "$0"`

# Determine the Java command to use.
DEFAULT_JVM_OPTS='"--add-opens" "java.base/java.util=ALL-UNNAMED" "--add-opens" "java.base/java.lang=ALL-UNNAMED" "--add-opens" "java.base/java.lang.invoke=ALL-UNNAMED" "--add-opens" "java.base/java.util=ALL-UNNAMED"'

# Use gradlew to build
cd "$DIRNAME"
./gradlew "$@"
